Task 3
AnastasiiaSidorenko/reactjs-mentoring pull request #3
Opened 2022-06-21 18:44 UTC by AnastasiiaSidorenko

2022-06-28 13:52 UTC, Dmitry-White commented
Any updates? :)

2022-06-30 15:09 UTC, AnastasiiaSidorenko commented
> 



> Any updates? :)

In progress :)

2022-07-11 21:38 UTC, Dmitry-White requested changes
Looks great!
Left some comments for improvement ;)
by the way, glad you're back on track!

2022-07-11 21:38 UTC, Dmitry-White commented on movies-app/src/Header/Header.jsx
> +          + ADD MOVIE
The "+" sign could be generalised as an icon. And UI elements might have different icons (think of those "house", "email" or "phone" icons some UIs have).
Therefore, it makes sense to create Icon component(s) and update Button component to conditionally use it inline next to the actual text.

2022-07-11 21:38 UTC, Dmitry-White commented on movies-app/src/MovieCard/MovieCard.jsx
> +      <img className="movie-card__image" src={`assets/movieImages/${image}.png`} alt="movie" />
Consider creating a "constants" folder under "src/core" where all the main reusable non-react things will be stored.
"constants" will hold any number of file to your liking - as long as they contain all the hard-coded numbers/strings that you use throughout the app. The idea is to have a central place for all the constants to be able to easily reuse/change them.
Once all the constants are in "src/core/constants" don't forget to go through the app and use them where applicable.

2022-07-11 21:38 UTC, Dmitry-White commented on movies-app/src/MoviesCollection/MoviesCollection.jsx
> +          <p>SORT BY</p>
I can see that you're using a lot of raw user-facing strings which is not extendable and error-prone.
Under "src/core" folder that you create after one of the above comments consider creating a folder "i18y" which stands for "internationalization". This folder in real project usually holds translation object in cases when they're stored in the source code. The folder structure consists of "index.js" file and a number of "*.js" files for different languages (e.g. "en.js" for English or "ge.js" for German). Each of these language files contains an object with the same keys but different values for the target language. The idea behind it is to decouple the selected language for a website and the actual text used in all the components.

E.g. your "P" will have an image alt text in the JSX as follows:
`<p>{I18Y['EN'].SORT_BY}</p>` for English and `<p>{I18Y['GE'].SORT_BY}</p>` for German. As you might guess, this would allow to hook up language selection logic from your app that will pass either "EN" or "GE" to the I18Y object, but you the same "SORT_BY" key - and end up with different language texts displayed on the live website.

In the end, your task is to create such object (could be only English for now) and go though the whole app and change the hard-coded text to the usage of this I18Y object.

2022-07-16 13:01 UTC, AnastasiiaSidorenko commented
> Looks great! Left some comments for improvement ;) by the way, glad you're back on track!

Thank you :) The comments are resolved.

2022-07-20 16:14 UTC, Dmitry-White approved these changes

2022-07-22 22:03 UTC, merged